lines = [
"import { useState, useRef, useEffect, useCallback } from 'react'",
"",
"interface ISpeechRecognition extends EventTarget {",
"  lang: string; interimResults: boolean; maxAlternatives: number",
"  start(): void; stop(): void",
"  onstart:  ((e: Event) => void) | null",
"  onend:    ((e: Event) => void) | null",
"  onerror:  ((e: Event) => void) | null",
"  onresult: ((e: SpeechRecognitionEvent) => void) | null",
"}",
"interface SpeechRecognitionEvent extends Event {",
"  results: { [i: number]: { [j: number]: { transcript: string } } }",
"}",
"declare const SpeechRecognition: new () => ISpeechRecognition",
"declare const webkitSpeechRecognition: new () => ISpeechRecognition",
"",
"interface Message { role: 'user' | 'assistant'; content: string }",
"type AgentMode = 'llm' | 'local' | null",
"interface Props { onClose: () => void }",
"",
"// Voz predeterminada fija",
"const TTS_VOICE  = 'es-ES-ElviraNeural'",
"const TTS_PITCH  = 3",
"const TTS_SPEED  = 1.2",
"const TTS_EFFECT = 'reverb'",
"",
"export default function PumpkinModal({ onClose }: Props) {",
"  const [messages,   setMessages]  = useState<Message[]>([",
"    { role: 'assistant', content: '\U0001f383 \u00a1Hola! Soy el asistente del acuario. \u00bfEn qu\u00e9 te ayudo?' }",
"  ])",
"  const [input,      setInput]     = useState('')",
"  const [loading,    setLoading]   = useState(false)",
"  const [listening,  setListening] = useState(false)",
"  const [agentMode,  setAgentMode] = useState<AgentMode>(null)",
"  const [agentModel, setAgentModel] = useState('')",
"  const [muted,      setMuted]     = useState(false)",
"",
"  const mutedRef  = useRef(false)",
"  const audioRef  = useRef<HTMLAudioElement | null>(null)",
"  const bottomRef = useRef<HTMLDivElement>(null)",
"  const inputRef  = useRef<HTMLInputElement>(null)",
"  const recoRef   = useRef<ISpeechRecognition | null>(null)",
"",
"  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages])",
"  useEffect(() => { inputRef.current?.focus() }, [])",
"",
"  async function speak(text: string) {",
"    if (mutedRef.current) return",
"    const prev = audioRef.current",
"    audioRef.current = null",
"    prev?.pause()",
"    try {",
"      const token = localStorage.getItem('oscario-token') ?? ''",
"      const resp = await fetch('/api/v1/tts', {",
"        method: 'POST',",
"        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },",
"        body: JSON.stringify({ text, voice: TTS_VOICE, engine: 'edge', pitch: TTS_PITCH, speed: TTS_SPEED, effect: TTS_EFFECT }),",
"      })",
"      if (!resp.ok) return",
"      const url = URL.createObjectURL(await resp.blob())",
"      const audio = new Audio(url)",
"      audioRef.current = audio",
"      audio.onended = () => { URL.revokeObjectURL(url); if (audioRef.current === audio) audioRef.current = null }",
"      await audio.play().catch(() => {})",
"    } catch { /* ignore */ }",
"  }",
"",
"  const sendMessage = useCallback(async (text: string) => {",
"    if (!text.trim() || loading) return",
"    setMessages(prev => [...prev, { role: 'user', content: text.trim() }])",
"    setInput(''); setLoading(true); setAgentMode(null)",
"    setMessages(prev => [...prev, { role: 'assistant', content: '' }])",
"    try {",
"      const token = localStorage.getItem('oscario-token') ?? ''",
"      const resp = await fetch('/api/v1/agent/chat', {",
"        method: 'POST',",
"        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },",
"        body: JSON.stringify({ message: text.trim(), history: messages.slice(-10) }),",
"      })",
"      if (!resp.ok || !resp.body) throw new Error('Error')",
"      const reader = resp.body.getReader(); const dec = new TextDecoder(); let buf = ''",
"      while (true) {",
"        const { done, value } = await reader.read()",
"        if (done) break",
"        buf += dec.decode(value, { stream: true })",
"        const parts = buf.split('\\n'); buf = parts.pop() ?? ''",
"        for (const line of parts) {",
"          if (!line.startsWith('data: ')) continue",
"          const raw = line.slice(6)",
"          if (raw === '[DONE]') break",
"          try {",
"            const p = JSON.parse(raw) as { token?: string; mode?: string; model?: string; provider?: string }",
"            if (p.mode) {",
"              setAgentMode(p.mode as AgentMode)",
"              if (p.model) setAgentModel(`${p.provider ? p.provider + ' \u2014 ' : ''}${p.model}`)",
"              continue",
"            }",
"            if (p.token) setMessages(prev => {",
"              const c = [...prev]; c[c.length-1] = { ...c[c.length-1], content: c[c.length-1].content + p.token }; return c",
"            })",
"          } catch { /* ignore */ }",
"        }",
"      }",
"    } catch {",
"      setMessages(prev => { const c = [...prev]; c[c.length-1] = { role: 'assistant', content: '\u274c Error al conectar con el agente.' }; return c })",
"    } finally {",
"      setLoading(false)",
"      setMessages(prev => {",
"        const last = prev[prev.length-1]",
"        if (last?.role === 'assistant' && last.content && !last.content.startsWith('\u274c')) void speak(last.content)",
"        return prev",
"      })",
"    }",
"  }, [loading, messages])",
"",
"  function handleKeyDown(e: React.KeyboardEvent) {",
"    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(input) }",
"    if (e.key === 'Escape') onClose()",
"  }",
"",
"  function toggleVoice() {",
"    const SR = (typeof SpeechRecognition !== 'undefined' && SpeechRecognition) ||",
"               (typeof webkitSpeechRecognition !== 'undefined' && webkitSpeechRecognition) || undefined",
"    if (!SR) { alert('Tu navegador no soporta reconocimiento de voz.'); return }",
"    if (listening && recoRef.current) { recoRef.current.stop(); setListening(false); return }",
"    const reco = new SR(); reco.lang = 'es-ES'; reco.interimResults = false; reco.maxAlternatives = 1",
"    reco.onstart = () => setListening(true); reco.onend = () => setListening(false); reco.onerror = () => setListening(false)",
"    reco.onresult = (e: SpeechRecognitionEvent) => sendMessage(e.results[0][0].transcript)",
"    recoRef.current = reco; reco.start()",
"  }",
"",
"  return (",
"    <div className=\"pk-overlay\" onClick={onClose}>",
"      <div className=\"pk-modal\" onClick={e => e.stopPropagation()}>",
"",
"        <div className=\"pk-header\">",
"          <div className=\"pk-title\">",
"            <span className=\"pk-icon\">\U0001f383</span>",
"            <div>",
"              <div style={{ fontWeight: 800, fontSize: '1rem' }}>Asistente del Acuario</div>",
"              <div style={{ fontSize: '.72rem', color: agentMode === 'llm' ? 'var(--teal)' : 'var(--t3)', display: 'flex', alignItems: 'center', gap: 4 }}>",
"                {agentMode === 'llm'",
"                  ? <><span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--teal)', display: 'inline-block' }} /> IA: {agentModel || 'Modelo externo'}</>",
"                  : agentMode === 'local'",
"                    ? <><span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--amber)', display: 'inline-block' }} /> Modo local</>",
"                    : 'Preg\u00fantame lo que quieras'}",
"              </div>",
"            </div>",
"          </div>",
"          <div style={{ display: 'flex', gap: 4, alignItems: 'center' }}>",
"            <button className=\"pk-close\" title={muted ? 'Activar voz' : 'Silenciar'} style={{ opacity: muted ? 0.4 : 1 }}",
"              onClick={() => { mutedRef.current = !mutedRef.current; setMuted(m => !m); if (mutedRef.current) { audioRef.current?.pause(); audioRef.current = null } }}>",
"              <i className={`fa-solid ${muted ? 'fa-volume-xmark' : 'fa-volume-high'}`} />",
"            </button>",
"            <button className=\"pk-close\" title=\"Cerrar\" onClick={() => { audioRef.current?.pause(); onClose() }}>",
"              <i className=\"fa-solid fa-xmark\" />",
"            </button>",
"          </div>",
"        </div>",
"",
"        <div className=\"pk-messages\">",
"          {messages.map((m, i) => (",
"            <div key={i} className={`pk-msg ${m.role}`}>",
"              {m.role === 'assistant' && <span className=\"pk-avatar\">\U0001f383</span>}",
"              <div className=\"pk-bubble\">",
"                {m.content || (loading && i === messages.length - 1",
"                  ? <span className=\"pk-typing\"><span /><span /><span /></span>",
"                  : '')}",
"              </div>",
"            </div>",
"          ))}",
"          <div ref={bottomRef} />",
"        </div>",
"",
"        <div className=\"pk-input-row\">",
"          <button className={`pk-voice-btn${listening ? ' listening' : ''}`} onClick={toggleVoice} title={listening ? 'Detener escucha' : 'Hablar'}>",
"            <i className={`fa-solid ${listening ? 'fa-stop' : 'fa-microphone'}`} />",
"          </button>",
"          <input ref={inputRef} className=\"pk-input\" placeholder={listening ? '\U0001f3999\ufe0f Escuchando...' : 'Escribe un mensaje...'}",
"            value={input} onChange={e => setInput(e.target.value)} onKeyDown={handleKeyDown} disabled={loading || listening} />",
"          <button className=\"pk-send-btn\" onClick={() => sendMessage(input)} disabled={!input.trim() || loading} title=\"Enviar\">",
"            <i className=\"fa-solid fa-paper-plane\" />",
"          </button>",
"        </div>",
"      </div>",
"    </div>",
"  )",
"}",
]

with open('x:/frontend/src/components/PumpkinModal.tsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('Done -', len(lines), 'lines')
