lines = [
"import { useState, useRef, useEffect, useCallback } from 'react'",
"import { createPortal } from 'react-dom'",
"",
"interface ISpeechRecognition extends EventTarget {",
"  lang: string; interimResults: boolean; maxAlternatives: number",
"  start(): void; stop(): void",
"  onstart:  ((e: Event) => void) | null",
"  onend:    ((e: Event) => void) | null",
"  onerror:  ((e: Event) => void) | null",
"  onresult: ((e: SpeechRecognitionEvent) => void) | null",
"}",
"interface SpeechRecognitionEvent extends Event {",
"  results: { [i: number]: { [j: number]: { transcript: string } } }",
"}",
"declare const SpeechRecognition: new () => ISpeechRecognition",
"declare const webkitSpeechRecognition: new () => ISpeechRecognition",
"",
"interface Message { role: 'user' | 'assistant'; content: string }",
"type AgentMode = 'llm' | 'local' | null",
"interface Props { onClose: () => void }",
"",
"type TtsEngine = 'edge' | 'piper'",
"type TtsEffect = 'none' | 'reverb' | 'echo' | 'robot' | 'cave'",
"",
"const EDGE_VOICES = [",
"  { name: 'es-ES-XimenaNeural',  label: 'Ximena',   desc: 'ES \u00b7 fem'  },",
"  { name: 'es-ES-AlvaroNeural',  label: '\u00c1lvaro',   desc: 'ES \u00b7 masc' },",
"  { name: 'es-ES-ElviraNeural',  label: 'Elvira',   desc: 'ES \u00b7 fem'  },",
"  { name: 'es-MX-DaliaNeural',   label: 'Dalia',    desc: 'MX \u00b7 fem'  },",
"  { name: 'es-MX-JorgeNeural',   label: 'Jorge',    desc: 'MX \u00b7 masc' },",
"  { name: 'es-MX-CarlotaNeural', label: 'Carlota',  desc: 'MX \u00b7 fem'  },",
"  { name: 'es-AR-ElenaNeural',   label: 'Elena',    desc: 'AR \u00b7 fem'  },",
"  { name: 'es-AR-TomasNeural',   label: 'Tom\u00e1s',    desc: 'AR \u00b7 masc' },",
"  { name: 'es-CO-SalomeNeural',  label: 'Salom\u00e9',   desc: 'CO \u00b7 fem'  },",
"  { name: 'es-US-PalomaNeural',  label: 'Paloma',   desc: 'US \u00b7 fem'  },",
"  { name: 'es-US-AlonsoNeural',  label: 'Alonso',   desc: 'US \u00b7 masc' },",
"  { name: 'es-BO-SofiaNeural',   label: 'Sof\u00eda',    desc: 'BO \u00b7 fem'  },",
"  { name: 'es-CL-CatalinaNeural',label: 'Catalina', desc: 'CL \u00b7 fem'  },",
"  { name: 'es-PE-CamilaNeural',  label: 'Camila',   desc: 'PE \u00b7 fem'  },",
"  { name: 'es-VE-PaolaNeural',   label: 'Paola',    desc: 'VE \u00b7 fem'  },",
"]",
"",
"const PIPER_VOICES = [",
"  { name: 'es_ES-davefx-medium',   label: 'Davefx',   desc: 'ES \u00b7 masc' },",
"  { name: 'es_ES-sharvard-medium', label: 'Sharvard', desc: 'ES \u00b7 fem'  },",
"  { name: 'es_MX-claude-high',     label: 'Claude',   desc: 'MX \u00b7 masc' },",
"  { name: 'es_ES-mls_10246-low',   label: 'MLS',      desc: 'ES \u00b7 fem'  },",
"]",
"",
"const EFFECTS: { id: TtsEffect; label: string }[] = [",
"  { id: 'none',  label: 'Sin efecto' },",
"  { id: 'reverb',label: 'Reverb'     },",
"  { id: 'echo',  label: 'Eco'        },",
"  { id: 'robot', label: 'Robot'      },",
"  { id: 'cave',  label: 'Cueva'      },",
"]",
"",
"const S: React.CSSProperties = {",
"  display: 'flex', flexDirection: 'column', gap: 0,",
"}",
"const row: React.CSSProperties = {",
"  display: 'flex', alignItems: 'center', gap: 8,",
"  padding: '5px 12px',",
"}",
"const label: React.CSSProperties = {",
"  fontSize: '.7rem', color: 'var(--t3)', minWidth: 52,",
"}",
"const sel: React.CSSProperties = {",
"  flex: 1, background: 'var(--surface)', color: 'var(--t1)',",
"  border: '1px solid var(--border)', borderRadius: 5, padding: '2px 4px',",
"  fontSize: '.78rem', cursor: 'pointer',",
"}",
"const sliderStyle: React.CSSProperties = {",
"  flex: 1, accentColor: 'var(--teal)',",
"}",
"const val: React.CSSProperties = {",
"  fontSize: '.7rem', color: 'var(--teal)', minWidth: 30, textAlign: 'right',",
"}",
"",
"export default function PumpkinModal({ onClose }: Props) {",
"  const [messages,   setMessages]  = useState<Message[]>([",
"    { role: 'assistant', content: '\U0001f383 \u00a1Hola! Soy el asistente del acuario. \u00bfEn qu\u00e9 te ayudo?' }",
"  ])",
"  const [input,      setInput]     = useState('')",
"  const [loading,    setLoading]   = useState(false)",
"  const [listening,  setListening] = useState(false)",
"  const [agentMode,  setAgentMode] = useState<AgentMode>(null)",
"  const [agentModel, setAgentModel] = useState('')",
"  const [muted,      setMuted]     = useState(false)",
"  const [voiceOpen,  setVoiceOpen] = useState(false)",
"  const [dropPos,    setDropPos]   = useState<{ top: number; right: number } | null>(null)",
"  // TTS settings",
"  const [engine,  setEngine]  = useState<TtsEngine>('edge')",
"  const [selVoice, setSelVoice] = useState('es-ES-XimenaNeural')",
"  const [pitch,   setPitch]   = useState(0)",
"  const [speed,   setSpeed]   = useState(1.0)",
"  const [effect,  setEffect]  = useState<TtsEffect>('none')",
"",
"  const mutedRef     = useRef(false)",
"  const ttsRef       = useRef({ engine: 'edge' as TtsEngine, voice: 'es-ES-XimenaNeural', pitch: 0, speed: 1.0, effect: 'none' as TtsEffect })",
"  const audioRef     = useRef<HTMLAudioElement | null>(null)",
"  const bottomRef    = useRef<HTMLDivElement>(null)",
"  const inputRef     = useRef<HTMLInputElement>(null)",
"  const recoRef      = useRef<ISpeechRecognition | null>(null)",
"  const sliderBtnRef = useRef<HTMLButtonElement>(null)",
"  const dropRef      = useRef<HTMLDivElement>(null)",
"",
"  // keep ttsRef in sync",
"  useEffect(() => { ttsRef.current = { engine, voice: selVoice, pitch, speed, effect } }, [engine, selVoice, pitch, speed, effect])",
"",
"  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages])",
"  useEffect(() => { inputRef.current?.focus() }, [])",
"",
"  useEffect(() => {",
"    if (!voiceOpen) return",
"    function onMD(e: MouseEvent) {",
"      if (sliderBtnRef.current?.contains(e.target as Node)) return",
"      if (dropRef.current?.contains(e.target as Node)) return",
"      setVoiceOpen(false)",
"    }",
"    document.addEventListener('mousedown', onMD)",
"    return () => document.removeEventListener('mousedown', onMD)",
"  }, [voiceOpen])",
"",
"  async function speak(text: string) {",
"    if (mutedRef.current) return",
"    audioRef.current?.pause(); audioRef.current = null",
"    try {",
"      const token = localStorage.getItem('oscario-token') ?? ''",
"      const { engine: eng, voice, pitch: p, speed: sp, effect: ef } = ttsRef.current",
"      const resp = await fetch('/api/v1/tts', {",
"        method: 'POST',",
"        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },",
"        body: JSON.stringify({ text, voice, engine: eng, pitch: p, speed: sp, effect: ef }),",
"      })",
"      if (!resp.ok) return",
"      const url = URL.createObjectURL(await resp.blob())",
"      const audio = new Audio(url)",
"      audioRef.current = audio",
"      audio.onended = () => URL.revokeObjectURL(url)",
"      audio.play()",
"    } catch { /* ignore */ }",
"  }",
"",
"  async function previewVoice() {",
"    audioRef.current?.pause(); audioRef.current = null",
"    void speak('Hola, soy el asistente del acuario. Puedo ayudarte con las luces y filtros.')",
"  }",
"",
"  const sendMessage = useCallback(async (text: string) => {",
"    if (!text.trim() || loading) return",
"    setMessages(prev => [...prev, { role: 'user', content: text.trim() }])",
"    setInput(''); setLoading(true); setAgentMode(null)",
"    setMessages(prev => [...prev, { role: 'assistant', content: '' }])",
"    try {",
"      const token = localStorage.getItem('oscario-token') ?? ''",
"      const resp = await fetch('/api/v1/agent/chat', {",
"        method: 'POST',",
"        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },",
"        body: JSON.stringify({ message: text.trim(), history: messages.slice(-10) }),",
"      })",
"      if (!resp.ok || !resp.body) throw new Error('Error')",
"      const reader = resp.body.getReader(); const dec = new TextDecoder(); let buf = ''",
"      while (true) {",
"        const { done, value } = await reader.read()",
"        if (done) break",
"        buf += dec.decode(value, { stream: true })",
"        const parts = buf.split('\\n'); buf = parts.pop() ?? ''",
"        for (const line of parts) {",
"          if (!line.startsWith('data: ')) continue",
"          const raw = line.slice(6)",
"          if (raw === '[DONE]') break",
"          try {",
"            const p = JSON.parse(raw) as { token?: string; mode?: string; model?: string; provider?: string }",
"            if (p.mode) {",
"              setAgentMode(p.mode as AgentMode)",
"              if (p.model) setAgentModel(`${p.provider ? p.provider + ' \u2014 ' : ''}${p.model}`)",
"              continue",
"            }",
"            if (p.token) setMessages(prev => {",
"              const c = [...prev]; c[c.length-1] = { ...c[c.length-1], content: c[c.length-1].content + p.token }; return c",
"            })",
"          } catch { /* ignore */ }",
"        }",
"      }",
"    } catch {",
"      setMessages(prev => { const c = [...prev]; c[c.length-1] = { role: 'assistant', content: '\u274c Error al conectar con el agente.' }; return c })",
"    } finally {",
"      setLoading(false)",
"      setMessages(prev => {",
"        const last = prev[prev.length-1]",
"        if (last?.role === 'assistant' && last.content && !last.content.startsWith('\u274c')) void speak(last.content)",
"        return prev",
"      })",
"    }",
"  }, [loading, messages])",
"",
"  function handleKeyDown(e: React.KeyboardEvent) {",
"    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(input) }",
"    if (e.key === 'Escape') onClose()",
"  }",
"",
"  function toggleVoice() {",
"    const SR = (typeof SpeechRecognition !== 'undefined' && SpeechRecognition) ||",
"               (typeof webkitSpeechRecognition !== 'undefined' && webkitSpeechRecognition) || undefined",
"    if (!SR) { alert('Tu navegador no soporta reconocimiento de voz.'); return }",
"    if (listening && recoRef.current) { recoRef.current.stop(); setListening(false); return }",
"    const reco = new SR(); reco.lang = 'es-ES'; reco.interimResults = false; reco.maxAlternatives = 1",
"    reco.onstart = () => setListening(true); reco.onend = () => setListening(false); reco.onerror = () => setListening(false)",
"    reco.onresult = (e: SpeechRecognitionEvent) => sendMessage(e.results[0][0].transcript)",
"    recoRef.current = reco; reco.start()",
"  }",
"",
"  const voices = engine === 'piper' ? PIPER_VOICES : EDGE_VOICES",
"",
"  return (",
"    <div className=\"pk-overlay\" onClick={onClose}>",
"      <div className=\"pk-modal\" onClick={e => e.stopPropagation()}>",
"",
"        <div className=\"pk-header\">",
"          <div className=\"pk-title\">",
"            <span className=\"pk-icon\">\U0001f383</span>",
"            <div>",
"              <div style={{ fontWeight: 800, fontSize: '1rem' }}>Asistente del Acuario</div>",
"              <div style={{ fontSize: '.72rem', color: agentMode === 'llm' ? 'var(--teal)' : 'var(--t3)', display: 'flex', alignItems: 'center', gap: 4 }}>",
"                {agentMode === 'llm'",
"                  ? <><span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--teal)', display: 'inline-block' }} /> IA: {agentModel || 'Modelo externo'}</>",
"                  : agentMode === 'local'",
"                    ? <><span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--amber)', display: 'inline-block' }} /> Modo local</>",
"                    : 'Preg\u00fantame lo que quieras'}",
"              </div>",
"            </div>",
"          </div>",
"          <div style={{ display: 'flex', gap: 4, alignItems: 'center' }}>",
"            <button ref={sliderBtnRef} className=\"pk-close\" title=\"Ajustes de voz\"",
"              onClick={() => {",
"                if (!voiceOpen && sliderBtnRef.current) {",
"                  const r = sliderBtnRef.current.getBoundingClientRect()",
"                  setDropPos({ top: r.bottom + 6, right: window.innerWidth - r.right })",
"                }",
"                setVoiceOpen(o => !o)",
"              }}>",
"              <i className=\"fa-solid fa-sliders\" />",
"            </button>",
"            <button className=\"pk-close\" title={muted ? 'Activar voz' : 'Silenciar'} style={{ opacity: muted ? 0.4 : 1 }}",
"              onClick={() => { mutedRef.current = !mutedRef.current; setMuted(m => !m); if (mutedRef.current) { audioRef.current?.pause(); audioRef.current = null } }}>",
"              <i className={`fa-solid ${muted ? 'fa-volume-xmark' : 'fa-volume-high'}`} />",
"            </button>",
"            <button className=\"pk-close\" title=\"Cerrar\" onClick={() => { audioRef.current?.pause(); onClose() }}>",
"              <i className=\"fa-solid fa-xmark\" />",
"            </button>",
"          </div>",
"        </div>",
"",
"        {voiceOpen && dropPos && createPortal(",
"          <div ref={dropRef} style={{ position: 'fixed', top: dropPos.top, right: dropPos.right, zIndex: 99999,",
"            background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 10, width: 260,",
"            boxShadow: '0 8px 32px #0009' }}>",
"",
"            {/* Header */}",
"            <div style={{ padding: '8px 12px 6px', fontSize: '.68rem', color: 'var(--t3)', borderBottom: '1px solid var(--border)',",
"              display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>",
"              <span>Ajustes de voz</span>",
"              <button style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--teal)', fontSize: '.78rem', padding: 0 }}",
"                onClick={previewVoice} title=\"Escuchar\">",
"                \u25b6 Probar",
"              </button>",
"            </div>",
"",
"            <div style={S}>",
"              {/* Motor */}",
"              <div style={row}>",
"                <span style={label}>Motor</span>",
"                <div style={{ display: 'flex', gap: 4, flex: 1 }}>",
"                  {(['edge', 'piper'] as TtsEngine[]).map(eng => (",
"                    <button key={eng}",
"                      style={{ flex: 1, padding: '3px 0', borderRadius: 5, fontSize: '.75rem', cursor: 'pointer',",
"                        border: '1px solid var(--border)',",
"                        background: engine === eng ? 'var(--teal)' : 'var(--surface)',",
"                        color: engine === eng ? '#fff' : 'var(--t2)' }}",
"                      onMouseDown={e => e.preventDefault()}",
"                      onClick={() => {",
"                        setEngine(eng)",
"                        setSelVoice(eng === 'piper' ? 'es_ES-davefx-medium' : 'es-ES-XimenaNeural')",
"                      }}>",
"                      {eng === 'edge' ? '\u2601\ufe0f Edge' : '\U0001f4bb Piper'}",
"                    </button>",
"                  ))}",
"                </div>",
"              </div>",
"",
"              {/* Voz */}",
"              <div style={row}>",
"                <span style={label}>Voz</span>",
"                <select style={sel} value={selVoice}",
"                  onChange={e => setSelVoice(e.target.value)}>",
"                  {voices.map(v => (",
"                    <option key={v.name} value={v.name}>{v.label} — {v.desc}</option>",
"                  ))}",
"                </select>",
"              </div>",
"",
"              <div style={{ height: 1, background: 'var(--border)', margin: '4px 0' }} />",
"",
"              {/* Tono */}",
"              <div style={row}>",
"                <span style={label}>Tono</span>",
"                <input type=\"range\" min={-8} max={8} step={1} value={pitch} style={sliderStyle}",
"                  onChange={e => setPitch(Number(e.target.value))} />",
"                <span style={val}>{pitch > 0 ? '+' : ''}{pitch}</span>",
"              </div>",
"",
"              {/* Velocidad */}",
"              <div style={row}>",
"                <span style={label}>Velocidad</span>",
"                <input type=\"range\" min={0.5} max={2.0} step={0.1} value={speed} style={sliderStyle}",
"                  onChange={e => setSpeed(Number(e.target.value))} />",
"                <span style={val}>{speed.toFixed(1)}x</span>",
"              </div>",
"",
"              {/* Efecto */}",
"              <div style={row}>",
"                <span style={label}>Efecto</span>",
"                <select style={sel} value={effect}",
"                  onChange={e => setEffect(e.target.value as TtsEffect)}>",
"                  {EFFECTS.map(ef => (",
"                    <option key={ef.id} value={ef.id}>{ef.label}</option>",
"                  ))}",
"                </select>",
"              </div>",
"",
"              {/* Reset */}",
"              <div style={{ ...row, justifyContent: 'flex-end', paddingTop: 4 }}>",
"                <button style={{ background: 'none', border: 'none', fontSize: '.68rem', color: 'var(--t3)', cursor: 'pointer', padding: 0 }}",
"                  onMouseDown={e => e.preventDefault()}",
"                  onClick={() => { setPitch(0); setSpeed(1.0); setEffect('none') }}>",
"                  \u21ba Restablecer",
"                </button>",
"              </div>",
"            </div>",
"          </div>,",
"          document.body",
"        )}",
"",
"        <div className=\"pk-messages\">",
"          {messages.map((m, i) => (",
"            <div key={i} className={`pk-msg ${m.role}`}>",
"              {m.role === 'assistant' && <span className=\"pk-avatar\">\U0001f383</span>}",
"              <div className=\"pk-bubble\">",
"                {m.content || (loading && i === messages.length - 1",
"                  ? <span className=\"pk-typing\"><span /><span /><span /></span>",
"                  : '')}",
"              </div>",
"            </div>",
"          ))}",
"          <div ref={bottomRef} />",
"        </div>",
"",
"        <div className=\"pk-input-row\">",
"          <button className={`pk-voice-btn${listening ? ' listening' : ''}`} onClick={toggleVoice} title={listening ? 'Detener escucha' : 'Hablar'}>",
"            <i className={`fa-solid ${listening ? 'fa-stop' : 'fa-microphone'}`} />",
"          </button>",
"          <input ref={inputRef} className=\"pk-input\" placeholder={listening ? '\U0001f3999\ufe0f Escuchando...' : 'Escribe un mensaje...'}",
"            value={input} onChange={e => setInput(e.target.value)} onKeyDown={handleKeyDown} disabled={loading || listening} />",
"          <button className=\"pk-send-btn\" onClick={() => sendMessage(input)} disabled={!input.trim() || loading} title=\"Enviar\">",
"            <i className=\"fa-solid fa-paper-plane\" />",
"          </button>",
"        </div>",
"      </div>",
"    </div>",
"  )",
"}",
]

with open('x:/frontend/src/components/PumpkinModal.tsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print('Done -', len(lines), 'lines')
